apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Corrected repo URL
    chart: wordpress
    helm:
      valueFiles:
      - custom-resources-mariadb-replication.yaml  # Ensure this path exists in your repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
