apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc  # Default Kubernetes API server
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    path: 'wordpress'
    targetRevision: 23.1.24
    chart: wordpress
    helm:
      valueFiles:
      - $values/custom-resources-mariadb-replication.yaml
      credentials:
      - docker-io-helm-oci  
  - repoURL: https://github.com/sshuen30/k8s-helm-chart-bitnami-wordpress.git  # URL of your Git repository
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
