apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc  # Default Kubernetes API server
  source:
    repoURL: https://github.com/sshuen30/k8s-helm-chart-bitnami-wordpress.git  # URL of your Git repository
    targetRevision: HEAD
    path: '.'  # Specify the path to your manifests (or use '.' for the root)
    helm:
      chart: https://charts.bitnami.com/bitnami/wordpress
      valueFiles:
        - custom-resources-mariadb-replication.yaml  # Optional values file
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
