apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc  # Default Kubernetes API server
  source:
    repoURL: https://github.com/sshuen30/k8s-helm-chart-bitnami-wordpress.git  # URL of your Git repository
    targetRevision: HEAD
    path: '.'  # Specify the path to your manifests (or use '.' for the root)
    helm:
      chart: oci://registry-1.docker.io/bitnamicharts/wordpress
      valueFiles:
        - custom-resources-mariadb-replication.yaml
      credentials:
        - docker-io-helm-oci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
