apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-wordpress-app
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc  # Default Kubernetes API server
  source:
    repoURL: 'https://your-repo-url.git'  # URL of your Git repository
    targetRevision: HEAD
    path: '.'  # Specify the path to your manifests (or use '.' for the root)
    helm:
      chart: oci://registry-1.docker.io/bitnamicharts/wordpress  # OCI Helm chart reference
      valueFiles:
        - custom-resources-mariadb-replication.yaml  # Optional values file
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
