apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-wordpress-app
  namespace: argocd  # Adjust if your ArgoCD installation uses a different namespace
spec:
  project: default  # Use your ArgoCD project name
  source:
    repoURL: 'https://github.com/sshuen30/k8s-helm-chart-bitnami-wordpress.git'  # Change to your GitHub repo URL
    targetRevision: HEAD
    path: .  # The path to your chart
    helm:
      valueFiles:
        - custom-resources-mariadb-replication.yaml  # Your custom values file
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress  # The namespace you want to deploy to
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources
      selfHeal: true  # Automatically sync if there are changes
